#!/bin/bash

exe="SQZ.EXE"
srcdir=`dirname "$0"`
exe="$srcdir/bin/$exe"

export EMU2_DRIVE_D="$srcdir/bin"
export EMU2_DRIVE_Z="/home"
export EMU2_CODEPAGE="866"

dospath()
{
  arg="$1"

  if [ ${arg:0:5} == "$EMU2_DRIVE_Z" ] ; then
    path=${arg:5}
    echo "Z:${path//\//\\}" | iconv -t "$EMU2_CODEPAGE"
  else
    echo "$arg"
  fi
}


cmd=("${exe}")

for arg in "${@}" ; do
  chr=${arg:0:1}
  if [ "$chr" == "/" ] || [ -e "$arg" ] ; then
    arg=`dospath "$arg"`
  elif [ "$chr" == "@" ] ; then
    arg=@`dospath "${arg:1}"`
  fi
  cmd+=("${arg}")
done

emu2 "${cmd[@]}"