#!/bin/bash

exe="UHARC.EXE"
srcdir=`dirname "$0"`
exe="$srcdir/bin/$exe"
set -- "wine" "$exe" "${@}"

# scriptkiddie lvl over 9000
script --return -qfc "`printf "%q " "${@}"`" /dev/null | sed -e "s/\x1B\[?25[hl]//g" | tr -d '\r'
