#!/bin/sh

# replace paths here
cmdtotal="/path/to/cmdTotal.exe"
plugin="/path/to/plugin.wcx"


opt=$1
ppath="`winepath -w "$plugin"`"
arc="`winepath -w "$2"`"

if [ -n "$3" ]; then
  filelist=$3
  target=$PWD
  tempdir=$(mktemp -d /tmp/multiarc.XXXXX)
  pushd "$tempdir"

  wine "$cmdtotal" "$ppath" "$opt" "$arc" "$tempdir" 2>/dev/null
  xargs -a "$filelist" cp --parents -Pft "$target"

  popd

  rm -r -f "$tempdir"
else
  wine "$cmdtotal" "$ppath" "$opt" "$arc" 2>/dev/null | grep "\->"
fi
