#!/bin/sh

# replace paths here
wcxtest="/path/to/wcxtest.exe"
plugin="/path/to/plugin.wcx"


opt=$1
ppath="`winepath -w "$plugin"`"
arc="`winepath -w "$2"`"

if [ -n "$3" ]; then
  filelist=$3
  target=$PWD
  tempdir=$(mktemp -d /tmp/multiarc.XXXXX)
  pushd "$tempdir"

  wine "$wcxtest" "$opt" "$ppath" "$arc"  2>/dev/null
  xargs -a "$filelist" cp --parents -Pft "$target"

  popd

  rm -r -f "$tempdir"
else
  wine "$wcxtest" "$opt" "$ppath" "$arc"  2>/dev/null
fi
